// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRecord(arg1) {
  return window['go']['main']['App']['AddRecord'](arg1);
}

export function ClearAllRecords() {
  return window['go']['main']['App']['ClearAllRecords']();
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function DeleteRecord(arg1) {
  return window['go']['main']['App']['DeleteRecord'](arg1);
}

export function ExitApp() {
  return window['go']['main']['App']['ExitApp']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetFavorites() {
  return window['go']['main']['App']['GetFavorites']();
}

export function GetRecords(arg1) {
  return window['go']['main']['App']['GetRecords'](arg1);
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function RecordFromPaste(arg1) {
  return window['go']['main']['App']['RecordFromPaste'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function ToggleFavorite(arg1) {
  return window['go']['main']['App']['ToggleFavorite'](arg1);
}

export function UpdateConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateConfig'](arg1, arg2, arg3);
}
