// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddRecord(arg1:string):Promise<void>;

export function ClearAllRecords():Promise<void>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function DeleteRecord(arg1:number):Promise<void>;

export function ExitApp():Promise<void>;

export function GetConfig():Promise<main.Config>;

export function GetFavorites():Promise<Array<main.ClipboardRecord>>;

export function GetRecords(arg1:string):Promise<Array<main.ClipboardRecord>>;

export function HideWindow():Promise<void>;

export function RecordFromPaste(arg1:string):Promise<void>;

export function SelectDirectory():Promise<string>;

export function ShowWindow():Promise<void>;

export function ToggleFavorite(arg1:number):Promise<string>;

export function UpdateConfig(arg1:string,arg2:number,arg3:string):Promise<void>;
